import os
API_ID = os.environ.get("API_ID", None) 
API_HASH = os.environ.get("API_HASH", None) 
BOT_TOKEN = os.environ.get("BOT_TOKEN", None) 
OPENAI_KEY = os.environ.get("OPENAI_KEY",None)
BOT_USERNAME = os.environ.get("BOT_USERNAME" ,None) 
SUDO=os.environ.get("SUDO","5611642776")
BOT_NAME = os.environ.get("BOT_NAME",None)
START_IMG = os.environ.get("START_IMG","https://graph.org/file/025822f0a3eef1d83141c.jpg")
STKR = os.environ.get("STKR","CAACAgUAAxkBAAEJv_lkuSxhgXLywGTjAQF_vntMpu-K0wACgAkAAmIDMVaFziDW7hG1dS8E")
BANNED_USERS=os.environ.get("BANNED_USERS",None)
UPDATE_CHNL = os.environ.get("UPDATE_CHNL",None)
OWNER_USERNAME = os.environ.get("OWNER_USERNAME",None)
SUDO=os.environ.get("SUDO","5611642776")
SUPPORT_GRP = os.environ.get("SUPPORT_GRP",None)
